POST http://localhost:3000/login/ 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI
Content-Type:application/json 

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
### API 2 
GET http://localhost:3000/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI

### API 3
GET http://localhost:3000/states/1/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI

### API 4
POST http://localhost:3000/districts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI
Content-Type:application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

### API 5 
GET http://localhost:3000/districts/1/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI

### API 7

PUT http://localhost:3000/districts/6/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### API 8
GET http://localhost:3000/states/5/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzAyOTg5MjQyfQ.FF32fbr9y9SkiqrdizsWhIHOiPRq29kzY4Cxu8zemRI